### PR TITLE
fix(rrule): restore before/after compatibility mapping

### LINKED ISSUE #499: TypeError: this._rrule.before is not a function in v0.26.0
### Description
After upgrading to v0.26.0, calling `rrule.before()` or `rrule.after()` on a VEVENT object causes a crash.

### Root Cause
In `ical.js`, the `RRuleCompatWrapper` class attempts to call `.before()` and `.after()` on the underlying
`rrule-temporal` instance. However, `rrule-temporal` implements these methods as `.previous()` and `.next()`
respectively.

### Steps to Reproduce
1. Use `node-ical` v0.26.0.
2. Parse an ICS with a recurring event (RRULE).
3. Call `event.rrule.before(someDate)`.

### Minimal Reproduction Code
  import ical from 'node-ical';

  const icsData = `BEGIN:VCALENDAR
  VERSION:2.0
  BEGIN:VEVENT
  DTSTART:20230101T090000Z
  RRULE:FREQ=DAILY;COUNT=5
  SUMMARY:Test Event
  END:VEVENT
  END:VCALENDAR`;

  const events = ical.sync.parseICS(icsData);
  const event = Object.values(events).find(e => e.type === 'VEVENT');

  // This will throw TypeError: this._rrule.before is not a function
  event.rrule.before(new Date());

### Actual Result
`TypeError: this._rrule.before is not a function`
at `RRuleCompatWrapper.before` (node_modules/node-ical/ical.js:171:32)

### Expected Result
It should return the occurrence before the specified date, matching the `rrule.js` API behavior.

### Suggested Fix
In `ical.js`, update `RRuleCompatWrapper` methods:
- `before(date, inclusive)` should call `this._rrule.previous(date, inclusive)`
- `after(date, inclusive)` should call `this._rrule.next(date, inclusive)`

### Environment
- node-ical version: 0.26.0
- Node.js version:  v22.18.0

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
Map wrapper methods to rrule-temporal API:
- before() -> previous()
- after() -> next()

That should have happened during the migration from rrule to rrule-temporal (#422).

I also added a regression test to ensure event.rrule.before()/after() work and return the expected Date values without throwing.

Fixes #499.

## Summary by CodeRabbit

* **Bug Fixes**
  * RRULE `before()` and `after()` methods now correctly identify preceding and following occurrences in recurrence patterns.

* **Tests**
  * Added test verifying RRULE API compatibility with recurring events containing occurrence limits.

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
@coderabbitai review

**Comment by KristjanESPERANTO** [comment]
@jens-maus coderabbit seems satisfied. Did you noticed this PR? :slightly_smiling_face:
